# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
      timezone: 'America/Los_Angeles'
    groups:
      patch-and-minor-updates:
        applies-to: version-updates
        update-types:
          - 'patch'
          - 'minor'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 25.x'

  - package-ecosystem: 'docker'
    directory: '/server'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:15'
      timezone: 'America/Los_Angeles'
    groups:
      docker-images:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/worker'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:15'
      timezone: 'America/Los_Angeles'
    groups:
      docker-images:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/handbrake'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:15'
      timezone: 'America/Los_Angeles'
    groups:
      docker-images:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:15'
      timezone: 'America/Los_Angeles'
    groups:
      docker-images:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:30'
      timezone: 'America/Los_Angeles'
    groups:
      github-actions:
        patterns:
          - '*'
