# ATTENTION:
# if you download this file directly, please ensure to rename it to 'compose.yaml'

services:
  handbrake-server:
    image: ghcr.io/viciros/handbrake-web-server:latest
    container_name: handbrake-web-server
    restart: unless-stopped
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 9999:9999
    volumes:
      - /path/to/your/data:/data
      - /path/to/your/downloads:/downloads # choose as the default input path in Settings
      - /path/to/your/encoded:/encoded # choose as the default output path in Settings

  handbrake-worker:
    image: ghcr.io/viciros/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    restart: unless-stopped
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    environment:
      - WORKER_ID=handbrake-worker-nvidia # give your worker a unique name
      - WORKER_TOKEN=copy-token-created-in-workers-page # create this on the Workers page
      - SERVER_URL=handbrake-server # change if setting up a standalone worker, prefix with http(s):// if necessary
      - SERVER_PORT=9999 # change if using a reverse proxy or the port is otherwise different than above
    volumes:
      - /mnt/cache/handbrake-web-worker-tmp:/tmp/handbrake-web # worker temp space for active transcodes
    depends_on:
      - handbrake-server
    deploy: # this allows the container to access your gpu resources
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
